version: "3.3"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: easydoc123
