version: "3.3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - "db"
    command: ["uvicorn", "easydoc_api.app:app", "--host=0.0.0.0", "--port=8087", "--reload"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: appuser
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: easydoc
      AI_CLIENT_ID: ${AI_CLIENT_ID}
      AI_CLIENT_SECRET: ${AI_CLIENT_SECRET}

  ui:
    build:
      context: ./ui/easydoc-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - "db"
      - "api"
    command: ["ng", "serve", "--host=0.0.0.0"]  # for local test/demo

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
