version: "3.3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - "db"
    command: ["uvicorn", "easydoc_api.app:app", "--host=0.0.0.0", "--port=8087", "--reload"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: appuser
      DB_PASSWORD: appuser123
      DB_NAME: easydoc
      AI_CLIENT_ID: "1tmjf97gr48os5p5tpebpim0f2"
      AI_CLIENT_SECRET: "1a12fp2h1j13q02cnp3c44ltv5qot49fr8dpvsr6u48faqpj2535"

  ui:
    build:
      context: ./ui/easydoc-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - "db"
      - "api"
    command: ["ng", "serve", "--host=0.0.0.0"]  # for local test/demo

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: easydoc123
