CREATE USER appuser WITH PASSWORD '__DB_PASSWORD_PLACEHOLDER__';
CREATE DATABASE easydoc;

\c easydoc

-- following two CREATE TABLE statements are generated by sqlalchemy from db_models.py
-- regenerate if required

CREATE TABLE invoice_info (
        invoice_id CHAR(36) NOT NULL, 
        issuer_name VARCHAR NOT NULL, 
        issuer_address VARCHAR, 
        recipient_name VARCHAR, 
        document_date DATE, 
        payment_date DATE, 
        due_date DATE, 
        currency CHAR(3), 
        amount_total NUMERIC NOT NULL, 
        amount_paid NUMERIC, 
        amount_tax NUMERIC, 
        amount_due NUMERIC, 
        amount_sum NUMERIC, 
        num_items INTEGER, 
        create_date TIMESTAMP DEFAULT now() NOT NULL, 
        update_date TIMESTAMP DEFAULT now() NOT NULL, 
        deleted BOOLEAN DEFAULT 'false' NOT NULL, 
        PRIMARY KEY (invoice_id)
);

CREATE TABLE invoice_item (
        item_id INTEGER GENERATED BY DEFAULT AS IDENTITY, 
        invoice_id CHAR(36), 
        item_name VARCHAR, 
        sub_total NUMERIC, 
        create_date TIMESTAMP DEFAULT now() NOT NULL, 
        update_date TIMESTAMP DEFAULT now() NOT NULL, 
        deleted BOOLEAN DEFAULT 'false' NOT NULL, 
        PRIMARY KEY (item_id), 
        FOREIGN KEY(invoice_id) REFERENCES invoice_info (invoice_id)
);

GRANT SELECT, UPDATE, INSERT ON invoice_info TO appuser;
GRANT SELECT, UPDATE, INSERT ON invoice_item TO appuser;
