run:
	DB_HOST="localhost" DB_USER="appuser" DB_PASSWORD="appuser123" DB_NAME="easydoc" AI_CLIENT_ID="1tmjf97gr48os5p5tpebpim0f2" AI_CLIENT_SECRET="1a12fp2h1j13q02cnp3c44ltv5qot49fr8dpvsr6u48faqpj2535" uvicorn easydoc_api.app:app -host=0.0.0.0 --port=8000 --reload
